name: Advanced CI Pipeline

on:
  push:
    branches:
      - feature
      - Develop
  pull_request:
    branches:
      - feature
      - Develop

  schedule:
    - cron: '30 11 * * 3,5'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build Project
        run: mvn clean package -DskipTests | tee build.log

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: target/*.jar

  sonarcloud:
            runs-on: self-hosted
            needs: build
            steps:
              - name: Checkout Repository
                uses: actions/checkout@v4
        
              - name: Set Up Java
                uses: actions/setup-java@v3
                with:
                  distribution: 'temurin'
                  java-version: '17'
                  cache: 'maven'
        
              - name: Run SonarCloud Analysis
                env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                run: |
                  mvn sonar:sonar `
                    -Dsonar.projectKey=Abhishek01062500_MVCWeb `
                    -Dsonar.organization=abhishek01062500 `
                    -Dsonar.host.url=https://sonarcloud.io `
                     -Dsonar.branch.name=feature `
                    -Dsonar.login=$SONAR_TOKEN
                shell : powershell
  test:
    runs-on: self-hosted
    needs: build
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Unit Tests
        run: |
            mvn test | Tee-Object -FilePath test-output.log
            if ($LASTEXITCODE -ne 0) {
              Write-Host "❌ Tests failed!"
              exit 1
            }
        shell: powershell  
        
        

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

  code-coverage:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: target/site/jacoco/

  deploy:
    runs-on: self-hosted
    needs: test
    if: success()  # ✅ Deploy only if tests & coverage succeed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Application
        run: echo "🚀 Deploying application..."  # Replace with actual deployment script

  notify:
    runs-on: self-hosted
    needs: [build, test, code-coverage, deploy]
    if: failure()  # ✅ Send email if any job fails
    steps:
      - name: Log Failure
        run: echo "❌ Build failed! Check logs for details."

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.PASSWORD }}
          subject: "🚨 GitHub Actions Build Failed!"
          body: |
            ❌ The CI/CD pipeline for Java MVC application has **failed**.
            📅 Timestamp: $(date)
            🔗 Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            **Failure Details:**
            - Build Log: build.log
            - Test Log: test-output.log
            - Coverage Log: coverage-output.log
            
            Please take immediate action!
          to: ${{ secrets.MAIL_RECEIVER }}
          from: ${{ secrets.USERNAME }}
