name: CI Pipeline

on:
  push:
    branches:
      - feature
      - develop
      
  pull_request:
    branches:
      - feature #both branches PUSH PULL
      - develop
  schedule:
    - cron: "30 11 * * 3,5"  # Runs every Wednesday & Friday at 5 PM IST (11:30 AM UTC)

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository #checkout
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Eclipse Temurin JDK
          java-version: '17'       # Change this to match your project's Java version
          cache: 'maven'

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: target/*.jar

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Unit Tests
        run: mvn test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
